version: '3'
services:
  mariadb:
    build: ./mariadb
    image: mariadb/genius
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mongs
    ports:
      - '13306:3306'
  php-apache:
    build: ./php-apache
    image: php-apache/genius
    container_name: php-apache
    volumes:
      - /opt/Bird:/var/www/html
    links:
      - mariadb
    ports:
      - '80:80'
